# GSM8K Math Reasoning Task Configuration
task_name: "gsm8k"
task_type: "causal_lm"

# Model Configuration
model:
  name_or_path: "mistralai/Mistral-7B-v0.1"
  trust_remote_code: true
  use_auth_token: true

# PEFT Configuration
peft:
  method: "lora"
  lora_r: 32
  lora_alpha: 64
  lora_dropout: 0.05
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"
  inference_mode: false

# Dataset Configuration
dataset:
  name: "gsm8k"
  subset: "main"
  train_split: "train"
  eval_split: "test"
  test_split: null
  text_column: null
  label_column: null
  max_length: 1024
  preprocessing_num_workers: 8
  
  # Prompt template for GSM8K
  prompt_template: |
    Question: {question}
    
    Answer: Let's solve this step by step.
    {answer}

# Training Arguments
training:
  output_dir: "./outputs/gsm8k"
  num_train_epochs: 5
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 4
  learning_rate: 0.0002  # 2e-4
  weight_decay: 0.01
  warmup_ratio: 0.05
  lr_scheduler_type: "cosine"
  
  # Evaluation
  eval_strategy: "steps"
  eval_steps: 200
  save_strategy: "steps"
  save_steps: 200
  load_best_model_at_end: false
  
  # Optimization
  fp16: false
  bf16: true
  gradient_checkpointing: true
  optim: "paged_adamw_8bit"
  max_grad_norm: 1.0
  
  # Logging
  logging_steps: 10
  logging_dir: "./outputs/gsm8k/logs"
  report_to: ["tensorboard"]
  
  # Misc
  seed: 42
  data_seed: 42
  remove_unused_columns: false
  save_total_limit: 2

# SFT Specific
sft:
  max_seq_length: 1024
  packing: false
  dataset_text_field: "text"

# Accelerate Configuration
accelerate:
  mixed_precision: "bf16"
  gradient_accumulation_steps: 4
  use_cpu: false
