# MetaMathQA Task Configuration
task_name: "metamath_qa"
task_type: "CAUSAL_LM"

# Model Configuration
model:
  name_or_path: "meta-llama/Llama-2-7b-hf"  # Can use: mistralai/Mistral-7B-v0.1, etc.
  trust_remote_code: true
  use_auth_token: true  # Set to true if using gated models

# PEFT Configuration
peft:
  method: "lora"
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"

# Dataset Configuration
dataset:
  name: "meta-math/MetaMathQA"
  subset: null
  train_split: "train"
  eval_split: "train[:5000]"  # Use a subset for validation
  test_split: null
  text_column: null  # Will be formatted in code
  label_column: null
  max_length: 2048
  preprocessing_num_workers: 8
  
  # Prompt template for math problems
  prompt_template: |
    Below is an instruction that describes a task. Write a response that appropriately completes the request.
    
    ### Instruction:
    {query}
    
    ### Response:
    {response}

# Training Arguments
training:
  output_dir: "./outputs/metamath_qa"
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 8
  learning_rate: 0.0002  # 2e-4
  weight_decay: 0.0
  warmup_ratio: 0.03
  lr_scheduler_type: "cosine"
  
  # Evaluation
  eval_strategy: "steps"
  eval_steps: 500
  save_strategy: "steps"
  save_steps: 500
  load_best_model_at_end: false
  
  # Optimization
  fp16: false
  bf16: true  # Use bf16 for better numerical stability with large models
  gradient_checkpointing: true
  optim: "paged_adamw_32bit"
  max_grad_norm: 0.3
  
  # Logging
  logging_steps: 10
  logging_dir: "./outputs/metamath_qa/logs"
  report_to: ["tensorboard"]
  
  # Misc
  seed: 42
  data_seed: 42
  remove_unused_columns: false
  save_total_limit: 3
  
# SFT Specific
sft:
  max_seq_length: 2048
  packing: false
  dataset_text_field: "text"

# Accelerate Configuration
accelerate:
  mixed_precision: "bf16"
  gradient_accumulation_steps: 8
  use_cpu: false
