# Base Configuration Template
# Copy and modify this file for your custom tasks

task_name: "custom_task"
task_type: "causal_lm"  # or "classification"

# Model Configuration
model:
  name_or_path: "meta-llama/Llama-2-7b-hf"  # Change to your model
  trust_remote_code: true
  use_auth_token: false  # Set to true for gated models

# PEFT Configuration
peft:
  method: "lora"
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]  # Adjust for your model
  bias: "none"
  task_type: "CAUSAL_LM"  # or "SEQ_CLS" for classification

# Dataset Configuration
dataset:
  name: "your-username/your-dataset"
  subset: null
  train_split: "train"
  eval_split: "validation"
  test_split: null
  text_column: null
  label_column: null
  max_length: 2048
  preprocessing_num_workers: 8
  
  # Prompt template - customize based on your data
  prompt_template: |
    Input: {input}
    Output: {output}

# Training Arguments
training:
  output_dir: "./outputs/custom_task"
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 8
  learning_rate: 0.0002  # 2e-4
  weight_decay: 0.0
  warmup_ratio: 0.03
  lr_scheduler_type: "cosine"
  
  # Evaluation
  eval_strategy: "steps"
  eval_steps: 500
  save_strategy: "steps"
  save_steps: 500
  load_best_model_at_end: false
  
  # Optimization
  fp16: false
  bf16: true
  gradient_checkpointing: true
  optim: "paged_adamw_32bit"
  max_grad_norm: 1.0
  
  # Logging
  logging_steps: 10
  logging_dir: "./outputs/custom_task/logs"
  report_to: ["tensorboard"]
  
  # Misc
  seed: 42
  data_seed: 42
  remove_unused_columns: false
  save_total_limit: 3

# SFT Specific (for causal_lm tasks)
sft:
  max_seq_length: 2048
  packing: false
  dataset_text_field: "text"

# Accelerate Configuration
accelerate:
  mixed_precision: "bf16"
  gradient_accumulation_steps: 8
  use_cpu: false
